language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION -ne '3.4' ]]; then pip install dill; fi
  - "python setup.py install"
# command to run tests
script: python tests.py
sudo: false
